<a href="https://colab.research.google.com/github/petersonrs/projetostack/blob/main/Koalas01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Caminhos dos dados

In [33]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [34]:
clientes = '/content/drive/MyDrive/Colab Notebooks/StackKoala/cru/olist_customers_dataset.csv'
lista_pedidos = '/content/drive/MyDrive/Colab Notebooks/StackKoala/cru/olist_order_items_dataset.csv'
pgto_pedidos = '/content/drive/MyDrive/Colab Notebooks/StackKoala/cru/olist_order_payments_dataset.csv'
avaliacoes_pedidos = '/content/drive/MyDrive/Colab Notebooks/StackKoala/cru/olist_order_reviews_dataset.csv'
pedidos = '/content/drive/MyDrive/Colab Notebooks/StackKoala/cru/olist_orders_dataset.csv'
produtos = '/content/drive/MyDrive/Colab Notebooks/StackKoala/cru/olist_products_dataset.csv'
vendedores = '/content/drive/MyDrive/Colab Notebooks/StackKoala/cru/olist_sellers_dataset.csv'
categoria_produtos = '/content/drive/MyDrive/Colab Notebooks/StackKoala/cru/product_category_name_translation.csv'

## Import libs

In [35]:
import pandas as pd

## lendo os csvs

In [36]:
ds_lista_pedidos = pd.read_csv(lista_pedidos, index_col=False, encoding='utf8')
ds_pgto_pedidos = pd.read_csv(pgto_pedidos, index_col=False, encoding='utf8')
ds_avaliacoes_pedidos = pd.read_csv(avaliacoes_pedidos, index_col=False, encoding='utf8')
ds_pedidos = pd.read_csv(pedidos, index_col=False, encoding='utf8')
ds_produtos = pd.read_csv(produtos, index_col=False, encoding='utf8')
ds_vendedores = pd.read_csv(vendedores, index_col=False, encoding='utf8')
ds_clientes = pd.read_csv(clientes, index_col=False, encoding='utf8')
ds_categoria_produtos = pd.read_csv(categoria_produtos, index_col=False, encoding='utf8')

## join entre as tabelas para montar um tabeão

In [37]:
result = ds_pedidos.merge(ds_lista_pedidos, on="order_id", how="left")

In [38]:
result = result.merge(ds_produtos, on='product_id', how='left')

In [39]:
result = result.merge(ds_vendedores, on='seller_id', how='left')

In [40]:
result = result.merge(ds_clientes, on='customer_id', how='left')

In [41]:
result = result.merge(ds_avaliacoes_pedidos, on='order_id', how='left')

In [42]:
result = result.merge(ds_pgto_pedidos, on='order_id', how='left')

## exibindo como ficaram junções

In [43]:
result.head(5)

                           order_id  ... payment_value
0  e481f51cbdc54678b7cc49136f2d6af7  ...         18.12
1  e481f51cbdc54678b7cc49136f2d6af7  ...          2.00
2  e481f51cbdc54678b7cc49136f2d6af7  ...         18.59
3  53cdb2fc8bc7dce0b6741e2150273451  ...        141.46
4  47770eb9100c2d0c44946d9cf07ec65d  ...        179.12

[5 rows x 39 columns]

## backup do resultado e store na pasta de dados processados

In [44]:
transformacao_final = result

In [49]:
transformacao_final.to_csv('/content/drive/MyDrive/Colab Notebooks/StackKoala/processado/dados_transformados.csv',  index=False, encoding='utf8')

In [45]:
transformacao_final.head(2)

                           order_id  ... payment_value
0  e481f51cbdc54678b7cc49136f2d6af7  ...         18.12
1  e481f51cbdc54678b7cc49136f2d6af7  ...          2.00

[2 rows x 39 columns]

In [20]:
transformacao_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 119151 entries, 0 to 119150
Data columns (total 39 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119151 non-null  object
 1   customer_id                    119151 non-null  object
 2   order_status                   119151 non-null  object
 3   order_purchase_timestamp       119151 non-null  object
 4   order_approved_at              118974 non-null  object
 5   order_delivered_carrier_date   117065 non-null  object
 6   order_delivered_customer_date  115730 non-null  object
 7   order_estimated_delivery_date  119151 non-null  object
 8   order_item_id                  118318 non-null  float64
 9   product_id                     118318 non-null  object
 10  seller_id                      118318 non-null  object
 11  shipping_limit_date            118318 non-null  object
 12  price                          118318 non-null  float64
 13  freight_value                  118318 non-null  float64
 14  product_category_name          116609 non-null  object
 15  product_name_lenght            116609 non-null  float64
 16  product_description_lenght     116609 non-null  float64
 17  product_photos_qty             116609 non-null  float64
 18  product_weight_g               118298 non-null  float64
 19  product_length_cm              118298 non-null  float64
 20  product_height_cm              118298 non-null  float64
 21  product_width_cm               118298 non-null  float64
 22  seller_zip_code_prefix         118318 non-null  float64
 23  seller_city                    118318 non-null  object
 24  seller_state                   118318 non-null  object
 25  customer_unique_id             119151 non-null  object
 26  customer_zip_code_prefix       119151 non-null  int64
 27  customer_city                  119151 non-null  object
 28  customer_state                 119151 non-null  object
 29  review_id                      119151 non-null  object
 30  review_score                   119151 non-null  int64
 31  review_comment_title           14189 non-null   object
 32  review_comment_message         51250 non-null   object
 33  review_creation_date           119151 non-null  object
 34  review_answer_timestamp        119151 non-null  object
 35  payment_sequential             119148 non-null  float64
 36  payment_type                   119148 non-null  object
 37  payment_installments           119148 non-null  float64
 38  payment_value                  119148 non-null  float64
dtypes: float64(14), int64(2), object(23)
memory usage: 36.4+ MB

In [46]:
#transformacao_final = transformacao_final.drop(columns=['review_comment_title'], axis=1)
#transformacao_final.head(5)

In [47]:
transformacao_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 119151 entries, 0 to 119150
Data columns (total 39 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119151 non-null  object
 1   customer_id                    119151 non-null  object
 2   order_status                   119151 non-null  object
 3   order_purchase_timestamp       119151 non-null  object
 4   order_approved_at              118974 non-null  object
 5   order_delivered_carrier_date   117065 non-null  object
 6   order_delivered_customer_date  115730 non-null  object
 7   order_estimated_delivery_date  119151 non-null  object
 8   order_item_id                  118318 non-null  float64
 9   product_id                     118318 non-null  object
 10  seller_id                      118318 non-null  object
 11  shipping_limit_date            118318 non-null  object
 12  price                          118318 non-null  float64
 13  freight_value                  118318 non-null  float64
 14  product_category_name          116609 non-null  object
 15  product_name_lenght            116609 non-null  float64
 16  product_description_lenght     116609 non-null  float64
 17  product_photos_qty             116609 non-null  float64
 18  product_weight_g               118298 non-null  float64
 19  product_length_cm              118298 non-null  float64
 20  product_height_cm              118298 non-null  float64
 21  product_width_cm               118298 non-null  float64
 22  seller_zip_code_prefix         118318 non-null  float64
 23  seller_city                    118318 non-null  object
 24  seller_state                   118318 non-null  object
 25  customer_unique_id             119151 non-null  object
 26  customer_zip_code_prefix       119151 non-null  int64
 27  customer_city                  119151 non-null  object
 28  customer_state                 119151 non-null  object
 29  review_id                      119151 non-null  object
 30  review_score                   119151 non-null  int64
 31  review_comment_title           14189 non-null   object
 32  review_comment_message         51250 non-null   object
 33  review_creation_date           119151 non-null  object
 34  review_answer_timestamp        119151 non-null  object
 35  payment_sequential             119148 non-null  float64
 36  payment_type                   119148 non-null  object
 37  payment_installments           119148 non-null  float64
 38  payment_value                  119148 non-null  float64
dtypes: float64(14), int64(2), object(23)
memory usage: 36.4+ MB

In [54]:
transformacao_final.head(5)

                           order_id  ... payment_value
0  e481f51cbdc54678b7cc49136f2d6af7  ...         18.12
1  e481f51cbdc54678b7cc49136f2d6af7  ...          2.00
2  e481f51cbdc54678b7cc49136f2d6af7  ...         18.59
3  53cdb2fc8bc7dce0b6741e2150273451  ...        141.46
4  47770eb9100c2d0c44946d9cf07ec65d  ...        179.12

[5 rows x 39 columns]